website:
  title: "Lourenço Xavier"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - href: about.qmd
        text: About
      - text: "Data Visualization"
        menu:
          - text: "Erasmus receiving cities"
            href: erasmus_destinations.qmd
          - text: "Eurovision points per country"
            href: eurovision.qmd
      - text: "Text Analysis"
        menu:
          - text: "New York Times headlines"
            href: newyorktimes.qmd

format:
  html:
    theme: minty
    css: styles.css
