project:
  type: website
  output-dir: docs
website:
  title: "lourenco-xavier.github.io"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - about.qmd
      - data_viz.qmd

format:
  html:
    theme: minty
      
      
    css: styles.css
    toc: true

editor: visual

