project:
  type: website
  output-dir: docs

title: "Lourenço Xavier"
navbar:
  left:
    - text: Home
      href: index.html
    - text: About
      href: about.html
    - text: Data Visualization
      href: data_viz.html

format:
  html:
    theme: minty
    css: styles.css
    toc: true

editor: visual
