project:
  type: website
  output-dir: docs

website:
  title: "Lourenço Xavier"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - href: about.qmd
        text: About
      - href: data_viz.qmd
        text: Data Visualization

format:
  html:
    theme: minty
    css: styles.css
    toc: true

editor: visual
