project:
  type: website
  output-dir: docs

title: "Lourenço Xavier"
navbar:
  left:
    - href: index.qmd
      text: Home
    - about.qmd
    - data_viz.qmd

format:
  html:
    theme: minty
    css: styles.css
    toc: true

editor: visual
