project:
  type: website
  output-dir: docs

website:
  title: "Lourenço Xavier"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - href: about.qmd
        text: About
      - text: "Data Visualization"
        menu:
          - text: "Erasmus receiving cities"
            href: erasmus_destinations.qmd
          - text: "Eurovision points per country"
            href: eurovision.qmd
      - text: "Text Analysis"
        menu:
          - text: "New York Times headlines"
            href: newyorktimes.qmd
      - text: "Simulations"
        menu:
          - text: "Room with an Ocean view"
            href: ocean_view.qmd
      - text: "Data Science Ethics"
        menu:
          - text: "Dutch childcare benefits scandal"
            href: dutch_data_ethics.qmd


format:
  html:
    theme: minty
    css: styles.css
