project:
  type: website
  output-dir: docs

website:
  title: "Lourenço Xavier"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - href: about.qmd
        text: About
      - text: "Data Visualization"
        menu:
          - text: "Erasmus receiving cities"
            href: erasmus_destinations.qmd

format:
  html:
    theme: minty
    css: styles.css
    toc: true

editor: visual
